export enum ErrorCode {
  UNAUTHORIZED = 'UNAUTHORIZED',
  INVALID_KEY = 'INVALID_KEY',
  WRONG_KEY_TYPE = 'WRONG_KEY_TYPE',
  RATE_LIMITED = 'RATE_LIMITED',
  MISSING_FIELDS = 'MISSING_FIELDS',
  INVALID_INPUT = 'INVALID_INPUT',
  TIER_LIMIT_EXCEEDED = 'TIER_LIMIT_EXCEEDED',
  INSUFFICIENT_BALANCE = 'INSUFFICIENT_BALANCE',
  RULE_VIOLATION = 'RULE_VIOLATION',
  VAULT_EXISTS = 'VAULT_EXISTS',
  VAULT_CREATE_FAILED = 'VAULT_CREATE_FAILED',
  SWAP_FAILED = 'SWAP_FAILED',
  PREDICTION_FAILED = 'PREDICTION_FAILED',
  NO_PREDICTION_WALLET = 'NO_PREDICTION_WALLET',
  KYC_REQUIRED = 'KYC_REQUIRED',
  MARKET_UNAVAILABLE = 'MARKET_UNAVAILABLE',
  MARKET_NOT_FOUND = 'MARKET_NOT_FOUND',
  MARKET_CLOSED = 'MARKET_CLOSED',
  CARD_FROZEN = 'CARD_FROZEN',
  MERCHANT_BLOCKED = 'MERCHANT_BLOCKED',
  AGENT_LIMIT = 'AGENT_LIMIT',
  PARTNER_SUSPENDED = 'PARTNER_SUSPENDED',
  NOT_FOUND = 'NOT_FOUND',
  INTERNAL = 'INTERNAL',
  UNKNOWN = 'UNKNOWN',
}

export class ClawVaultError extends Error {
  public readonly code: string;
  public readonly statusCode: number;

  constructor(code: string, message: string, statusCode: number) {
    super(message);
    this.name = 'ClawVaultError';
    this.code = code;
    this.statusCode = statusCode;
  }
}
